<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class InspeksiPrinter extends Model
{
    use HasFactory;

    protected $fillable = [
        'pica_number',
        'created_date',
        'condition',
        'inspection_at',
        'month',
        'year',
        'inspection_status',
        'pic',
        'crew',
        'skidding_condition',
        'skidding_condition_text',
        'engsel_solpan_condition',
        'engsel_solpan_condition_text',
        'door_engsel_condition',
        'door_engsel_condition_text',
        'mt_color',
        'mt_color_text',
        'rope_for_moving_mt',
        'rope_for_moving_mt_text',
        'cleanliness_condition_mt_area',
        'cleanliness_condition_mt_area_text',
        'sticker_kip',
        'sticker_kip_text',
        'pole_condition',
        'pole_condition_text',
        'padlock_panel_condition',
        'padlock_panel_condition_text',
        'voltage_battery',
        'voltage_battery_text',
        'battery_cabel_condition',
        'battery_cabel_condition_text',
        'connector_battery_condition',
        'battery_suite',
        'battery_suite_text',
        'box_battery_cleanliness_condition',
        'box_battery_cleanliness_condition_text',
        'voltage_mppt_spek_solpan',
        'voltage_mppt_spek_solpan_text',
        'solpan_circuit_cable',
        'solpan_circuit_cable_text',
        'connections_between_solpan',
        'connections_between_solpan_text',
        'cleanliness_condition_solpan',
        'cleanliness_condition_solpan_text',
        'circuit_condition_box_output',
        'circuit_condition_box_output_text',
        'stepup_voltage',
        'stepup_voltage_text',
        'mcb_matches_output',
        'mcb_matches_output_text',
        'connections_cable_condition',
        'connections_cable_condition_text',
        'remarks',
        'due_date',
        'necessary',
        'location',
        'location_detail',
        'approved_by',
        'status_approval',
        'findings1',
        'findings2',
        'findings3',
        'findings1_image',
        'findings2_image',
        'findings3_image',
        'findings_action1',
        'findings_action2',
        'findings_action3',
        'findings_action_image1',
        'findings_action_image2',
        'findings_action_image3',
    ];
}
